id: I00EE10DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T03:01:30+00:00'
last_modified: '2022-06-15T16:34:47.567305+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG26107
  title: འབྲུག་པ་སངས་རྒྱས་རྡོ་རྗེའི་གསུང་སྔོན་འགྲོའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A461:
      image_group_id: I1KG26335
      title: Volume 1 of 'brug pa sangs rgyas rdo rje'i gsung sngon 'gro'i skor/
      total_pages: 122
      order: 1
      base_file: A461.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
