id: opecha:P000333
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG26107
  title: འབྲུག་པ་སངས་རྒྱས་རྡོ་རྗེའི་གསུང་སྔོན་འགྲོའི་སྐོར།
  volume:
    148baa0c91424fc5af11f2fe3551962d:
      image_group_id: I1KG26335
      title: Volume 1 of 'brug pa sangs rgyas rdo rje'i gsung sngon 'gro'i skor/
      volume_number: 1
      total_pages: 122
  author: ''
ebook_metadata:
  title: འབྲུག་པ་སངས་རྒྱས་རྡོ་རྗེའི་གསུང་སྔོན་འགྲོའི་སྐོར།
  author: ''
  sku: P000333
  cover: cover.jpg
  layers:
  - pagination
